### ISSUE TITLE
Question: How does the template handle error or offline?

### ISSUE THREAD

**Issue by iamrobert** [Lyquix/tpl_lyquix#13]
Great template.

How does the template handle:

- offline
- error

Protostar has offline.php /error.php files. 

I'm curious as whenever I call my:

echo $this->params->get() from template.xml it results in an error for those files.

**Comment by lyquix-owner** [comment]
Hello @iamrobert  , thanks for your message

You are right, both the error and offline templates are very limited when trying to access any parameters from the template. 

You can see that in early versions of this template we had an error.php file: https://github.com/Lyquix/tpl_lyquix/blob/315789cbf1849e4c4ea39636dc3a31a19c0f6e35/error.php

But we removed it because it wasn't working well without the parameters from the template. Additionally, since we use sh404sef component, we can customize 404 errors from there without the need for the error.php template. And we never used the offline.php template.

So we decided to let Joomla fallback to the system templates.
